/**
 * Build both halves of the plugin.
 *
 * Host half: an ESM bundle for Node, with every `@deepseek-ai/*` package left
 * external so the harness resolves its own copies.
 *
 * Client half: the dsh dynamic browser bundle format — one
 * `window.__ModuleLoader__.load({ id, factory })` registration whose factory
 * receives `require` for the platform module table (React, Cordis, the shared
 * client libraries). The CJS body esbuild produces is wrapped exactly as
 * `packages/client/tsdown.client.ts` declares it: the factory defines
 * `module`/`exports`, and the emitted `module.exports` is returned.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))

/** Module table seeded by the web shell (`packages/client/web/src/platform.ts`). */
const PLATFORM_MODULES = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
]

const banner = '// Generated by scripts/build.mjs — edit src/ and rebuild.'

await mkdir(resolve(root, 'lib'), { recursive: true })

await build({
  entryPoints: [resolve(root, 'src/index.ts')],
  outfile: resolve(root, 'lib/index.js'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  // The harness owns these packages; the plugin only reads their types.
  external: ['@deepseek-ai/*'],
  banner: { js: banner },
  logLevel: 'warning',
})

const client = await build({
  entryPoints: [resolve(root, 'src/client/index.tsx')],
  bundle: true,
  write: false,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  jsx: 'automatic',
  external: PLATFORM_MODULES,
  legalComments: 'none',
  logLevel: 'warning',
})

const body = client.outputFiles[0].text
const requires = [...new Set([...body.matchAll(/require\("([^"]+)"\)/gu)].map(match => match[1]))]
const undeclared = requires.filter(specifier => !PLATFORM_MODULES.includes(specifier))
if (undeclared.length > 0) {
  throw new Error(`client bundle requires modules outside the platform table: ${undeclared.join(', ')}`)
}

const wrapped = [
  '// Generated by scripts/build.mjs — edit src/ and rebuild.',
  `window.__ModuleLoader__.load({ id: ${JSON.stringify(pkg.name)}, factory: (require) => {`,
  'var module = { exports: {} }; var exports = module.exports;',
  body,
  'return module.exports; } });',
  '',
].join('\n')

await writeFile(resolve(root, 'lib/client.js'), wrapped, 'utf8')
console.log(`built lib/index.js and lib/client.js (client externals: ${requires.join(', ') || 'none'})`)
